-- MariaDB Script generated by MySQL Workbench
-- Tue Dec 12 23:23:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Create the PSIRT schema 
CREATE DATABASE PSIRT;

-- Use the PSIRT schema
USE PSIRT;

-- Create the association table for Orders and Animal
CREATE TABLE Animal(
    OrderID INT NOT NULL,
    AnimalType VARCHAR(3) NOT NULL,
    PRIMARY KEY (OrderID, AnimalType),
    CONSTRAINT FK_OrderID_Animal FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
    CONSTRAINT FK_AnimalType FOREIGN KEY (AnimalType) REFERENCES Animal(AnimalType)
    );

-- Create the User table
CREATE TABLE User (
    User_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LastName VARCHAR(45) NOT NULL,
    FirstName VARCHAR(45) NOT NULL,
    Role ENUM('client', 'sitter', 'handler') NOT NULL,
    Phone VARCHAR(20),
    EmailAddress VARCHAR(45),
    Password VARCHAR(45) NOT NULL
);

CREATE TABLE Orders (
    OrderID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ServiceState ENUM('pending', 'assigned', 'completed') NOT NULL DEFAULT 'pending',
    ClientID INT,
    HandlerID INT,
    SitterID INT,
    OrderDate DATETIME,
    DueDate DATETIME,
    CONSTRAINT FK_ClientID FOREIGN KEY (ClientID) REFERENCES User(User_ID),
    CONSTRAINT FK_HandlerID FOREIGN KEY (HandlerID) REFERENCES User(User_ID),
    CONSTRAINT FK_SitterID FOREIGN KEY (SitterID) REFERENCES User(User_ID)
    );

-- Create the IPAddresses table
CREATE TABLE IP_Addresses (
    UserID INT NOT NULL PRIMARY KEY,
    IPAddress VARCHAR(15) NOT NULL,
    CONSTRAINT FK_UserID FOREIGN KEY (UserID) REFERENCES User(User_ID)
);

-- Create the OrderComments table
CREATE TABLE Order_Comments (
    CommentID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    OrderNumber INT NOT NULL,
    ResponderID INT,
    CommentText LONGTEXT,
    CommentDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_OrderNumber FOREIGN KEY (OrderNumber) REFERENCES Orders(OrderID),
    CONSTRAINT FK_ResponderID FOREIGN KEY (ResponderID) REFERENCES User(User_ID)
);
